% AER E 351 Homework 03 Problem 3.9
% Matthew Mehrtens
clear, clc, close all;

%% Given
e = 2; % []

%% Problem 3.10a
delta = 2 * (90 - atand((e - 0.5) / 0.866)); % [°]
verify_delta = 2 * asind(1 / e); % [°]

%% Problem 3.10b
f_inf = 90 + atand(0.5 / 0.866); % [°]
verify_f_inf = 180 - acosd(1 / e); % [°]

%% Problem 3.10c
v_inf = sqrt(0.866^2 + (e - 0.5)^2); % [mu/h]
verify_v_inf = sqrt(e^2 - 1); % [mu/h]

%% Problem 3.10d
p_coeff = 1 / (e - 0.268); % []

%% Problem 3.10e
e_1 = 1.414;

%% Output
fprintf( ...
    "Problem 3.10 Solutions:\n" + ...
    "a:\n" + ...
    "delta = %g°\n" + ...
    "verification: delta = %g°\n" + ...
    "b:\n" + ...
    "f_inf = %g°\n" + ...
    "verification: f_inf = %g°\n" + ...
    "c:\n" + ...
    "v_inf = %g mu/h\n" + ...
    "verification: v_inf = %g mu/h\n" + ...
    "d:\n" + ...
    "Delta = %gp\n" + ...
    "e:\n" + ...
    "e = %g\n", ...
    delta, verify_delta, f_inf, verify_f_inf, v_inf, verify_v_inf, ...
    p_coeff, e_1);